# Update the APT Repository indices (Release & Package files)

name: pi4j-update-apt-repo

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: pi4j/pi4j-builder-repo

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - shell: bash
      env:
        PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
      run: |
        "$PGP_PRIVATE_KEY" > pi4j.pgp
        tree 

