# Update the APT Repository indices (Release & Package files)

name: pi4j-rebuild-repo

on:
  # Triggers the workflow on push events but only for the main branch when a Debian package file is added/modified/removed
  push:
    branches: [ main ]
    paths:
      - '**.deb'    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out 'main' branch of git repository
        uses: actions/checkout@v2
      - name: Extract PGP private key to file from GitHub secret
        run: 'echo "$PGP_PRIVATE_KEY" > pi4j.key'
        env:
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
      - name: Get latest docker builder image
        run: docker pull pi4j/pi4j-builder-repo:latest
      - name: Run [V1] build in docker builder container
        run: docker run --rm --volume $(pwd):/build pi4j/pi4j-builder-repo:latest .build/build-v1.sh
      - name: Run [V2] build in docker builder container
        run: docker run --rm --volume $(pwd):/build pi4j/pi4j-builder-repo:latest .build/build-v2.sh
      - name: Commit modified respository indices and push to git repository
        run: |
          git config --global user.email "bot@pi4j.com"
          git config --global user.name "Pi4J Bot"
          git status
          git add dists/.
          git commit -am "[AUTO] rebuild distribution respository indices"
          git push
      - name: Trigger dynamic README update of Pi4J/download
        env:
          GITHUB_PAT: ${{ secrets.PI4J_BOT_GITHUB_PAT }}
        run: >-
          curl
          --silent --show-error --fail --fail
          -X POST
          -H "Accept: application/vnd.github.v3+json"
          -H "Authorization: Token ${GITHUB_PAT}"
          https://api.github.com/repos/pi4j/download/actions/workflows/dynamic-readme.yml/dispatches
          -d '{"ref":"refs/heads/main"}'
